### PR TITLE
Incident Response Card and WebRCA Plugins

### PR DESCRIPTION
**Pull request by adamrdrew**
Unfortunately this is a fairly large PR. But we are doing multiple related things. We are adding the new Incident Response front page card. As part of that we were told to use the Web RCA backend plugin. The only way to do that was to bring webhRCA plugins into this monorepo and build and develop them here. So, we bring in the webRCA plugins. We also extend the backend a bit with a new pre-filtered public incidents route.

### CODE REVIEW

**Comment by adamrdrew** [comment]
Marking as draft until I've done RHDH integration testing because there's a lot going on here

**Comment by reavessm** [comment]
I haven't run this locally, so maybe it just blows up, but as a first look through, I like it.  It actually makes me want to take another pass through this and clean up some things in the frontend plugin.  There are a couple places where we can deduplicate some code, but I think we should get it working, get it up, then iterate

**Comment by adamrdrew** [comment]
@reavessm if you want to and have time running it locally should be as simple as:

1. Clone this branch
2. Set all of the environment variables in the app-config.yaml
3. Generate a catalog with entities that have webrca product annotations as required
3. `yarn install`
4. `yarn dev`

Your web RCA plugin will show up on all entity pages. The incident card will show up on the home page at `localhost:3000/home`

**Comment by reavessm** [comment]
So `yarn install` is failing for me I think its because `make build-all` is failing:

```
mv: cannot stat 'plugins/webrca-backend/'$'\n''> @redhatinsights/backstage-plugin-webrca-backend@1.1.0 prepack'$'\n''> backstage-cli package prepack'$'\n\n\n''> @redhatinsights/backstage-plugin-webrca-backend@1.1.0 postpack'$'\n''> backstage-cli package postpack'$'\n\n''redhatinsights-backstage-plugin-webrca-backend-1.1.0.tgz': No such file or directory
shasum: build/webrca-backend/
> @redhatinsights/backstage-plugin-webrca-backend@1.1.0 prepack
> backstage-cli package prepack


> @redhatinsights/backstage-plugin-webrca-backend@1.1.0 postpack
> backstage-cli package postpack

redhatinsights-backstage-plugin-webrca-backend-1.1.0.tgz: No such file or directory
SHA checksum:
./build.sh: line 44: build/webrca-backend/
> @redhatinsights/backstage-plugin-webrca-backend@1.1.0 prepack
> backstage-cli package prepack


> @redhatinsights/backstage-plugin-webrca-backend@1.1.0 postpack
> backstage-cli package postpack

redhatinsights-backstage-plugin-webrca-backend-1.1.0-integrity.txt: No such file or directory
make: *** [Makefile:16: build-webrca-backend] Error 1
```

I'm pretty sure my plugins need `yarn tsc` before `yarn export-dynamic`  I normally build with [these instructions](https://github.com/RedHatInsights/backstage-plugin-web-rca/blob/main/backend/package.json#L43).

`yarn tsc` in the backend directory fails because it can't find the frontend:

```
> yarn
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@redhatinsights/backstage-plugin-webrca-frontend@^0.1.0" required by "app@0.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@redhatinsights/backstage-plugin-webrca-backend@^0.1.0" required by "backend@0.0.0" on the "npm" registry.
    at /usr/lib/node_modules_20/yarn/lib/package-request.js:187:17
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules_20/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/lib/node_modules_20/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@redhatinsights/backstage-plugin-webrca-frontend@^0.1.0" required by "app@link:packages/app" on the "npm" registry.
    at /usr/lib/node_modules_20/yarn/lib/package-request.js:187:17
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules_20/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/lib/node_modules_20/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm not sure why the backend plugin is trying to pull in the frontend as a dependency...

**Comment by adamrdrew** [comment]
@reavessm If you pull the latest versions it might work. I fixed some version numbers. Also the docs are updated.

**Comment by adamrdrew** [comment]
Manual integration testing with RHDH succeeded. I was able to use all visual-qontract and webrca functions with this PR.

**Comment by adamrdrew** [comment]
@reavessm also make sure you are using node 18

**Comment by reavessm** [comment]
> @reavessm also make sure you are using node 18

```
> node --version
v20.17.0
```

oh

**Comment by reavessm** [comment]
Ok, I was able to get it to build and run locally.  A simple patch gets rid of an error I found in `packages/app/src/components/EntityPage.tsx`:

```diff
diff --git a/plugins/webrca-frontend/src/index.ts b/plugins/webrca-frontend/src/index.ts
index caa3fe8..525aa44 100644
--- a/plugins/webrca-frontend/src/index.ts
+++ b/plugins/webrca-frontend/src/index.ts
@@ -1 +1 @@
-export { webRcaPlugin, WebRcaPage } from './plugin';
+export { webRcaPlugin, WebRCAFetchComponent } from './plugin';
diff --git a/plugins/webrca-frontend/src/plugin.ts b/plugins/webrca-frontend/src/plugin.ts
index 42109ee..ff28b6e 100644
--- a/plugins/webrca-frontend/src/plugin.ts
+++ b/plugins/webrca-frontend/src/plugin.ts
@@ -7,9 +7,9 @@ export const webRcaPlugin = createPlugin({
   id: 'web-rca',
 });
 
-export const WebRcaPage = webRcaPlugin.provide(
+export const WebRCAFetchComponent = webRcaPlugin.provide(
   createComponentExtension({
-    name: 'WebRcaPage',
+    name: 'WebRCAFetchComponent',
     component: {
       lazy: () =>
         import('./components/WebRCAFetchComponent').then(m => m.WebRCAFetchComponent),
```

Then, of course re`export-dynamic`, and re`yarn install`

**Comment by adamrdrew** [comment]
Good catch. There was actually a simpler fix, which was just to export `WebRCAFetchComponent` from the index of the frontend package.

**Pull request merged**
